title = "BTL LTW"
institution = "Vietnam National University - Ho Chi Minh City University of Technology"
semester = 242
major = "Computer Science"
faculty = "Computer Science and Engineer"

[course]
name = "LTW"
id = "CO3049"

[committee]
id = 12
secretary = "Nguyễn Quang Hùng"

[[teachers]] 
name = "Thoại Nam" 
[[teachers]] 
name = "Diệp Thanh Đăng"

[[students]]
name = "Phạm Võ Quang Minh"
id = 2111762
[[students]]
name = "Võ Kiều My"
id = 6969696

[fonts]
serif = "Times New Roman"
monospace = "JetBrains Mono"
