title = "Music ecommerce website - hiPHoP"
institution = "Vietnam National University - Ho Chi Minh City University of Technology"
semester = 242
major = "Computer Science"
faculty = "Computer Science and Engineer"

[course]
name = "Web programming"
id = "CO3049"

[[teachers]] 
name = "Nguyễn Hữu Hiếu" 

[[students]]
name = "Phạm Võ Quang Minh"
id = 2111762
[[students]]
name = "Đỗ Nguyễn An Huy"
id = 2110193
[[students]]
name = "Nguyễn Đình Nam"
id = 2212136

[contacts]
email = "huy.do862003@hcmut.edu.vn"

[fonts]
serif = "Times New Roman"
monospace = "JetBrains Mono"
